### ISSUE TITLE
Multi-GPU

### ISSUE THREAD

**Issue by Jeiyoon** [SKT-AI/KoBART#10]
안녕하세요! 😄 

좋은 코드 정말 감사합니다 덕분에 한국어 large-scale model에 대해 열심히 공부하고 있습니다ㅎㅎ

혹시 NSMC benchmark classification task 코드인 nsmc.py 코드에서 

multi-gpu 사용 세팅은 어떻게 해야되는지 여쭤볼 수 있을까요? 

--gpus의 숫자를 단순히 바꾸면 오류가 나고,

> (AttributeError: Can't pickle local object 'get_cosine_schedule_with_warmup.<locals>.lr_lambda')

pytorch에서 일반적으로 사용하는 방법으로 수정하고 싶은데 디버거 모드로 찍어봐도 어려움이 있어서 이슈 남깁니다

감사합니다!

**Comment by haven-jeon** [comment]
PyTorchLightning 기반으로 작성되었으며, 아래 옵션으로 시도해 보시기 바랍니다. 

```
--gpus 2 --accelerator ddp
```

현재 사용할 수 있는 GPU가 없는 관계로 테스트가 어려운점 양해 부탁드립니다.

**Comment by Jeiyoon** [comment]
오오오

> --accelerator ddp

이 부분을 추가하니까 잘 동작하는걸 확인했습니다

자세한 내용은 PyTorchLightning에 대해 공부해보겠습니다

정말 감사합니다! 😄
