### ISSUE TITLE
어떻게 사용할 수 있는지 코드좀 알려주실수 있을까요?

### ISSUE THREAD

**Issue by sickkal** [SKT-AI/KoBART#11]
from kobart import get_kobart_tokenizer
kobart_tokenizer = get_kobart_tokenizer()
kobart_tokenizer.tokenize("안녕하세요. 한국어 BART 입니다.🤣:)l^o")
['▁안녕하', '세요.', '▁한국어', '▁B', 'A', 'R', 'T', '▁입', '니다.', '🤣', ':)', 'l^o']

도무지 이해가 안되네요
3줄까지 작성하고 
4줄에 print(kobart_tokenizer) 를 하면 괄호 [] 보기와 같이 나오는게 아닌가요;;

**Comment by haven-jeon** [comment]
`kobart_tokenizer.tokenize("안녕하세요. 한국어 BART 입니다.🤣:)l^o")`  + 엔터 하면 바로 프린트 됩니다. ^^

**Comment by sickkal** [comment]
버츄얼스튜디오 코드를 사용하고있는데 
위에 3줄 작성하고 플레이버튼을 눌러도 
터미널에 이렇게 나옵니다;
using cached model
PS C:\Users\qusdb\OneDrive\문서\GitHub\KoBertSum>

**Comment by haven-jeon** [comment]
Power Shell  환경에서는 테스트 되지 않았습니다. 
리눅스 환경에서 진행을 추천드립니다.

**Comment by haven-jeon** [comment]
답변이 없어 클로즈 합니다.
