### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'QUInt4x2Storage'

### ISSUE THREAD

**Issue by saitros** [SKT-AI/KoBART#12]
안녕하세요 
좋은소스 공유해주셔서 감사합니다

kobart translator 사용중에 해당 이슈가 발생합니다
원인을 찾던중 kobart install 이후에 해당 이슈가 발생하기 시작함을 확인했습니다

Torch == 1.7.1
pytorch-lightning == 1.1.0
python == 3.7.0

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/test_env/lib/python3.7/site-packages/torch/__init__.py", line 500, in <module>
    _C._initExtension(manager_path())
AttributeError: module 'torch' has no attribute 'QUInt4x2Storage'
```

어떤 오류인지 확인가능할까요?? 
좋은 자료 공유해주셔서 감사합니다!

**Comment by haven-jeon** [comment]
@seujung 혹시 확인해주실 수 있나요?

**Comment by seujung** [comment]
@haven-jeon 해당 사항 확인하고 의견 드리겠습니다.

**Comment by haven-jeon** [comment]
https://github.com/seujung/KoBART-translation 에 이슈를 올려주시면 감사하겠습니다. 해당 이슈는 클로즈 합니다.
