### ISSUE TITLE
Multi class classification 

### ISSUE THREAD

**Issue by nowgnas** [SKT-AI/KoBART#13]
안녕하세요!!

우선 좋은 코드 제공해 주셔서 감사합니다 :)

```
ValueError: The highest label in `target` should be smaller than the size of the `C` dimension of `preds`.
```
nsmc.py 코드로 7가지 클래스 분류를 하려고 합니다. validation step에서 위와 같은 오류가 발생합니다. 다중 클래스 분류를 위한 모델의 output 차원을 변경할 수 있는 방법이 궁금합니다.

감사합니다.

**Comment by haven-jeon** [comment]
https://github.com/SKT-AI/KoBART/blob/0636edf20390cbc72e8f676c6e8aeee086fd4f95/examples/nsmc.py#L211 에서 `num_labels=7`과 같이 추가해서 재정의해주시면 됩니다. 그럼 출력 텐서가 자동으로 7개 클래스가 됩니다.  자세한 내용은 https://huggingface.co/transformers/model_doc/bart.html#bartconfig 참고하세요. 

해당 이슈는 클로즈 합니다.
