### ISSUE TITLE
pip 설치 시 에러: Command errored out with exit status 128

### ISSUE THREAD

**Issue by qbranes** [SKT-AI/KoBART#15]
$ pip install git+https://github.com/SKT-AI/KoBART#egg=kobart --no-cache-dir -U turicreate

과 같이 설치 시도 시 아래와 같이 나타납니다(어느 OS에서든 비슷).  도움을 주실 수 있을까요? 

`
WARNING: Discarding git+https://github.com/SKT-AI/KoBART#egg=kobart. Command errored out with exit status 128: git clone -q https://github.com/SKT-AI/KoBART /private/var/folders/7d/8j9vj0c541z7y9gs0_3hdsrr0000gn/T/pip-install-89_v3_4e/kobart_aa1496bd8fd04a869d9a9e1e3fbe5782 Check the logs for full command output.
`
`
ERROR: Could not find a version that satisfies the requirement kobart (unavailable)
`
`
ERROR: No matching distribution found for kobart (unavailable)
`

**Comment by haven-jeon** [comment]
우분투 환경에서는 정상적으로 설치 되는걸 확인 했습니다. 

```
pip install git+https://github.com/SKT-AI/KoBART#egg=kobart --no-cache-dir -U turicreate
Collecting kobart
...
Installing collected packages: mpmath, llvmlite, sympy, numba, attr, resampy, prettytable, coremltools, turicreate
Successfully installed attr-0.3.1 coremltools-4.0b3 llvmlite-0.33.0 mpmath-1.2.1 numba-0.50.1 prettytable-0.7.2 resampy-0.2.1 sympy-1.9 turicreate-6.4.1
```

full command output을 좀더 확인해 보시는걸 추천드립니다.

**Comment by haven-jeon** [comment]
피드백이 없어 해당 이슈는 클로즈 합니다.
