### ISSUE TITLE
가중치 다운로드 서버의 도메인에 문제 발생

### ISSUE THREAD

**Issue by HojunCho** [SKT-AI/KoBART#17]
안녕하세요, 좋은 모델과 가중치를 배포해 주셔서 감사합니다.
다만 학습 가중치 도메인이 터져 현재 토큰나이저 및 가중치가 다운이 안되는 상황입니다.

![dns](https://user-images.githubusercontent.com/55834013/141242547-58a31e41-5de8-499e-94d2-7e111f2169ea.png)

혹시 확인해 주실 수 있으신가요?

**Comment by haven-jeon** [comment]
현재 Azure에서 서빙하던 모델 파일들이 모두 접근이 안되는거 같습니다. 
제 관리를 떠난 blob이다 보니.. 조치가 어렵네요. ㅜㅜ 현재 KoBERT도 같은 이슈가 있습니다.

https://github.com/SKTBrain/KoBERT/issues/67

일단 우회(허깅페이스 hub 이용)해서 쓰는 방법을 안내해 드립니다. 
같은 모델이니 아래와 같이 사용하셔도 큰 이슈 없을겁니다. 

```
from transformers import BartForConditionalGeneration, PreTrainedTokenizerFast, BartModel
tokenizer = PreTrainedTokenizerFast.from_pretrained('gogamza/kobart-base-v1')
model = BartModel.from_pretrained('gogamza/kobart-base-v1')
```

**Comment by honghungle** [comment]
> 현재 Azure에서 서빙하던 모델 파일들이 모두 접근이 안되는거 같습니다. 제 관리를 떠난 blob이다 보니.. 조치가 어렵네요. ㅜㅜ 현재 KoBERT도 같은 이슈가 있습니다.
> 
> [SKTBrain/KoBERT#67](https://github.com/SKTBrain/KoBERT/issues/67)
> 
> 일단 우회(허깅페이스 hub 이용)해서 쓰는 방법을 안내해 드립니다. 같은 모델이니 아래와 같이 사용하셔도 큰 이슈 없을겁니다.
> 
> ```
> from transformers import BartForConditionalGeneration, PreTrainedTokenizerFast, BartModel
> tokenizer = PreTrainedTokenizerFast.from_pretrained('gogamza/kobart-base-v1')
> model = BartModel.from_pretrained('gogamza/kobart-base-v1')
> ```

Hi. I'm tried to using tokenizer and model of kobart from Huggingface but I got new error:  **TypeError: forward() got an unexpected keyword argument 'labels'** when it tries to check Validation sanity. I haven't got this error when i using model and tokenizer from https://kobert.blob.core.windows.net/models/kobart
![Capture](https://user-images.githubusercontent.com/56141216/141689135-79bf0b6a-77fd-4d76-9ad1-255f8905104f.PNG)

**Comment by honghungle** [comment]
> > 현재 Azure에서 서빙하던 모델 파일들이 모두 접근이 안되는거 같습니다. 제 관리를 떠난 blob이다 보니.. 조치가 어렵네요. ㅜㅜ 현재 KoBERT도 같은 이슈가 있습니다.
> > [SKTBrain/KoBERT#67](https://github.com/SKTBrain/KoBERT/issues/67)
> > 일단 우회(허깅페이스 hub 이용)해서 쓰는 방법을 안내해 드립니다. 같은 모델이니 아래와 같이 사용하셔도 큰 이슈 없을겁니다.
> > ```
> > from transformers import BartForConditionalGeneration, PreTrainedTokenizerFast, BartModel
> > tokenizer = PreTrainedTokenizerFast.from_pretrained('gogamza/kobart-base-v1')
> > model = BartModel.from_pretrained('gogamza/kobart-base-v1')
> > ```
> 
> Hi. I'm tried to using tokenizer and model of kobart from Huggingface but I got new error: **TypeError: forward() got an unexpected keyword argument 'labels'** when it tries to check Validation sanity. I haven't got this error when i using model and tokenizer from https://kobert.blob.core.windows.net/models/kobart ![Capture](https://user-images.githubusercontent.com/56141216/141689135-79bf0b6a-77fd-4d76-9ad1-255f8905104f.PNG)

I fixed this problem. Thank you guys very much!

**Comment by haven-jeon** [comment]
해당 이슈는 우회 방법을 제안했으니 일단 클로즈 하겠습니다.

**Comment by bage79** [comment]
현재 모든 model, tokenzier, datasets 파일의 다운로드 및 코드의 실행이 정상으로 확인되었습니다.

혹시 다시 이슈가 발견되시면, 새로운 이슈로 재등록 부탁드립니다.
