### ISSUE TITLE
Pretrain 시 input구조에 대해서 질문드립니다!

### ISSUE THREAD

**Issue by reniew** [SKT-AI/KoBART#2]
Huggingface의 KoBART 모델쪽을 보니, `decoder_input_ids`가 입력값을 받지 않을 때는 아래와 같이 구성하는 것으로 확인했는데,

```
labels: t1, t2, t3,..., tn, eos, pad, pad
decoder_input_ids: eos, t1, t2, t3, 
```

혹시 pretrain시 `decoder_input_ids`를 직접 input넣어줄때 넣었는지, 혹은 `input_ids`, `labels`만 넣었는지 알 수 있을까요?
추가로 입력시 `input_ids`와 `labels`의 구조에 대해서 정확히 알 수 있을까요

ex)
```
input_ids = bos, t1, ..., tn, eos, pad, ...(mask포함)
labels = bos, t1, t2, ..., tn, eos, pad, ...
decoder_input_ids(직접 넣어줬다면) = bos, t1, t2, ..., tn, eos
```

마지막으로, 모델을 공유해주셔서 감사합니다.

**Comment by haven-jeon** [comment]
`decoder_input_ids`, `encoder_input_ids`를 모두 직접 코딩해서 BartModel에 넣어 학습했습니다.

**Comment by reniew** [comment]
혹시 special token은 각각 `encoder_input_ids`, `decoder_input_ids`, `labels` 모두 bos, eos가 앞뒤로 붙는 형태로 붙여서 넣으신건가요??

**Comment by haven-jeon** [comment]
공식 BART 학습 스크립트가 없어 논문 기준으로 아래와 같이 구현했습니다. 아마 이 부분은 여러 구현 방식이 있을 것으로 예상됩니다. 

KoBART 학습시 BOS, EOS는 문장 단위로 추가했습니다. 

인코더 디코더 와 레이블 입력은 아래와 같습니다. 

```
        # encoder in : s_0   s_1 s_2 <MASK> s_4 s_5
        # ecoder in : s_{-1}  s_0   s_1 s_2 s_3 s_4 s_5
        # label      :  s_0   s_1 s_2 s_3 s_4 s_5
```

512 토큰을 입력으로 full로 채웠고, paragraph가 구분될때는 다 채우지 않았습니다.

**Comment by haven-jeon** [comment]
별도 응답이 없어 close 하겠습니다.
