### ISSUE TITLE
example 에 있는 nsmc 로 파인튜닝된 모델을 어떻게 사용해야 하나요?

### ISSUE THREAD

**Issue by ghost** [SKT-AI/KoBART#24]
example 에 있는 nsmc.py 를 활용해서 8개 클래스를 분류하는 모델을 파인튜닝 했습니다.
학습 결과로 ckpt 파일과 hparams.yaml 파일을 얻었습니다.

요약 task 할 때는 KoBart summarization git 에서 예제 코드를 얻어서 파인튜닝한 모델을 사용했었는데요.
nsmc 쪽은 사용 예제가 없어서 어떻게 사용해야 하는지 모르겠어서 문의드립니다.

사용 예제나 참고할만한 링크라도 공유해주시면 감사하겠습니다.

**Comment by ghost** [comment]
huggingface 참조해서 해결했습니다.

**Comment by soom1017** [comment]
@hjchaeoml 안녕하세요, huggingface의 어떤 레포 참고하셨는지 알 수 있을까요?
