### ISSUE TITLE
pretrain/finetune시 사용했던 gpu

### ISSUE THREAD

**Issue by amy-hyunji** [SKT-AI/KoBART#4]
안녕하세요! 좋은 모델 공개해주셔서 감사합니다!

pretrain 및 finetune 당시 사용하셨던 gpu 스펙을 혹시 공유해주실 수 있으신가요?

감사합니다 :)

**Comment by haven-jeon** [comment]
내부 사정 때문에 GPU 스펙을 공개적으로 올리지 못하고 있습니다. 혹시 왜 그런지 알려주신다면 도움을 드릴 수 있을것 같습니다.

**Comment by haven-jeon** [comment]
응답이 없으셔서 close 합니다.
