### ISSUE TITLE
Pre-training objectives 관련 질문드립니다.

### ISSUE THREAD

**Issue by uoneway** [SKT-AI/KoBART#7]
안녕하세요.
소개페이지에는 Text Infilling에 대한 설명만 있어서 확인차 질문 드립니다.

- BART논문에서와 같이 
Pre-training objective를 Text Infilling + Sentence Shuffling 조합으로 training 시킨게 맞는지요?

- 그리고 혹시 데이터 중 Other corpus(0.27B)에 해당하는 데이터에 대한
조금 더 자세한 항목이나 비율 정보를 알려주실 수 있으실까요?
모두의 말뭉치에서 대화, 뉴스 외에 어떤 데이터를 이용하셨는지, 각 데이터의 개략적인 비율은 어떻게 되는지 궁금합니다.

좋은 모델 공개해주셔서 정말 감사합니다.

**Comment by haven-jeon** [comment]
> 
> 
> 안녕하세요.
> 소개페이지에는 Text Infilling에 대한 설명만 있어서 확인차 질문 드립니다.
> 
>     * BART논문에서와 같이
>       Pre-training objective를 Text Infilling + Sentence Shuffling 조합으로 training 시킨게 맞는지요?
> 
>     * 그리고 혹시 데이터 중 Other corpus(0.27B)에 해당하는 데이터에 대한
>       조금 더 자세한 항목이나 비율 정보를 알려주실 수 있으실까요?
>       모두의 말뭉치에서 대화, 뉴스 외에 어떤 데이터를 이용하셨는지, 각 데이터의 개략적인 비율은 어떻게 되는지 궁금합니다.
> 
> 
> 좋은 모델 공개해주셔서 정말 감사합니다.

README에 적어놓은 것 처럼 `Text Infilling`만을 사용해서 학습 했습니다.

**Comment by uoneway** [comment]
답변 감사합니다.
혹시 Sentence Shuffling은 적용하지 않으신 이유가 있으신지요?

**Comment by haven-jeon** [comment]
> Sentence Shuffling

두 목적함수의 성능차이가 작아서 간단하게 진행했습니다.

**Comment by uoneway** [comment]
아 그렇군요. 답변 감사합니다!

**Comment by haven-jeon** [comment]
이슈 클로즈 하겠습니다.
