### ISSUE TITLE
원문에서 요약문을 생성하는 예제 코드

### ISSUE THREAD

**Issue by thomassoh** [SKT-AI/KoBART#8]
주어진 원문에서 요약문을 생성하는 예제 코드를 알려주실 수 있나요?

**Comment by haven-jeon** [comment]
아래 링크에서 예제 코드를 제공하고 있습니다. 

https://github.com/seujung/KoBART-summarization

**Comment by thomassoh** [comment]
감사합니다. 이슈 닫습니다.

**Comment by thomassoh** [comment]
p{margin-top:0;margin-bottom:0}
    


    감사합니다.

--------- 원본 메일 ---------

    
        보낸사람: Heewon Jeon(gogamza) ***@***.***>
        받는사람: SKT-AI/KoBART ***@***.***>
        
            참조: thomassoh ***@***.***>, Author ***@***.***>
        
        날짜: 21.03.29 15:36 GMT +0900
        제목: Re: [SKT-AI/KoBART] 원문에서 요약문을 생성하는 예제 코드 (#8)
        
        
    
    
        

아래 링크에서 예제 코드를 제공하고 있습니다.

https://github.com/seujung/KoBART-summarization
