### ISSUE TITLE
KoBART Tokenizer를 사용한 한국어 QA Dataset의 Model Training 질문드립니다. 

### ISSUE THREAD

**Issue by nonmetal** [SKT-AI/KoBART#9]
안녕하세요.
우선 좋은 자료 공유해주셔서 감사드립니다.

현재 KoBART를 사용하여 QA task를 구현하기 위해서, Transformer에서 KoBART Tokenizer와 AutoModelForQuestionAnswering 모델을 사용하여 KorQuAD 1.0 Dataset을 Training 하고 있습니다. 
하지만 Training 과정에서 model save를 할 때 다음과 같은 오류가 발생하여 질문 드립니다. 

_[INFO|configuration_utils.py:329] 2021-04-28 16:20:12,610 >> Configuration saved in models/checkpoint-45000/config.json44998/56471 [5:26:32<1:22:42,  2.31it/s]
[INFO|modeling_utils.py:848] 2021-04-28 16:20:13,520 >> Model weights saved in models/checkpoint-45000/pytorch_model.bin
[INFO|tokenization_utils_base.py:1918] 2021-04-28 16:20:13,521 >> tokenizer config file saved in models/checkpoint-45000/tokenizer_config.json
[INFO|tokenization_utils_base.py:1924] 2021-04-28 16:20:13,521 >> Special tokens file saved in models/checkpoint-45000/special_tokens_map.json
[WARNING|tokenization_gpt2.py:288] 2021-04-28 16:20:13,619 >> Saving vocabulary to models/checkpoint-45000/merges.txt: BPE merge indices are not consecutive. Please check that the tokenizer is not corrupted!
[WARNING|tokenization_gpt2.py:288] 2021-04-28 16:20:13,620 >> Saving vocabulary to models/checkpoint-45000/merges.txt: BPE merge indices are not consecutive. Please check that the tokenizer is not corrupted!
..._

[model save를 담당하는 코드를 살펴보니 ](https://huggingface.co/transformers/_modules/transformers/tokenization_gpt2.html) merge.txt를 작성할 때에 bpe_tokens를 뽑아내게 되는데, 이 때에 index와 token_index가 같은 value가 아니게 되는 문제가 발생하는 것 같습니다. 이 오류가 Tokenization 오류인지 혹은 model 자체의 오류인지 혹시 확인 가능할까요? 

[Training은 이 코드를 통해서 이루어졌습니다.](https://github.com/jyjoon001/KoBART-KorQuAD/blob/main/run_squad_new.py)
감사합니다!

**Comment by haven-jeon** [comment]
huggingface tokenizer 인터페이스가 생각보다  다양해서 위 코드를 Autotokenizer 보다는 KoBART에 맞게(`PreTrainedTokenizerFast`) 고쳐서 학습하는게 어떨까 합니다. 그리고 모델 학습에서 merges.txt를 왜 작성하는지 저는 좀 이해가 되지 않네요. `tokenization_gpt2.py` 모듈이 왜 호출되는지도 이해가 가지 않구요..

**Comment by nonmetal** [comment]
안녕하세요! 
지적해주신 대로 `PreTrainedTokenizerFast` 를 사용하여 학습해 보도록 하겠습니다. 

또한, 모델 학습의 경우 다음과 같은 argument를 사용하였습니다. 

python3 ./run_squad_new.py --model_type kobart
                        --model_name_or_path hyunwoongko/kobart
                        --output_dir models
                        --data_dir data
                        --train_file KorQuAD_v1.0_train.json
                        --predict_file KorQuAD_v1.0_dev.json
                        --per_gpu_train_batch_size 8
                        --per_gpu_eval_batch_size 8
                        --max_seq_length 512
                        --logging_steps 5000
                        --save_steps 5000
                        --do_train

이 경우 save_step이 진행되는 수의 batch에서 model save를 진행하게 되는데, 이 때 
`torch.save(args, os.path.join(output_dir, "training_args.bin"))` 코드를 통해
merges.txt, tokenizer.json, vocab.json 등을 작성하면서 일어나는 현상이라고 생각합니다.

**Comment by nonmetal** [comment]
안녕하세요, 
`PreTrainedTokenizerFast`를 사용하여 Tokenization을 진행하던 중에 issue가 있어 질문드립니다. 

<img src="https://raw.githubusercontent.com/jyjoon001/KoBART-KorQuAD/main/kobart1.png" width="100%">

현재 `kobart_tokenizer` 를 사용하여 KorQuAD 데이터를 처리하려고 할 때, context와 question을 나누어주는 `cls_token`과 `sep_token`이 지정되지 않는 것을 확인할 수 있었습니다. 위의 결과에서 상단의 영문 파일은 SQuAD 데이터셋과 `facebook/bart-base` 모델을 사용하였으며, `<s>`,`</s>` 로 구분을 하는 것을 확인할 수 있었지만, 하단의 한글 파일(KorQuAD 데이터셋) 과 영문 파일 (SQuAD 데이터셋) 은 KoBART 토크나이저를 사용하여 Tokenizing을 하였지만 문단 경계가 구분되지 않는 문제가 발생하였습니다. 

<img src="https://raw.githubusercontent.com/jyjoon001/KoBART-KorQuAD/main/kobart2.png" width="60%">

혹시 이것이 `utils.py` 두 토큰을 지정해주지 않아서 일어나는 일이 아닌지 하고 생각하여 두 토큰에 대해서 정의를 하고 다시 모델을 실행시켰지만, 문단 경계를 구분해주지는 못했습니다. 이전 KoBERT에서는 `[CLS]`와 `[SEP]`으로 문단 간 경계를 나누어 주었던 것으로 기억하는데, 혹시 이 사항 관련해서 아직 KoBART 토크나이저가 QA 모델에 대해서는 호환되지 않는 것인지에 대해서 질문드리고 싶습니다.

[Tokenization은 Huggingface의 예제 Training code를 참고하였습니다. ](https://colab.research.google.com/drive/1LXAurLnP5518o_DxV1MuQK45WM1Y6iYf?usp=sharing)
감사합니다!

**Comment by haven-jeon** [comment]
BERT 인코더 구조에서 BART와 같은 인코더 디코더 구조로 변환해서 KorQuAD 작업을 하는건 당연히 기존 BERT 기반 방법이니 적용에 대해서는 추가적인 고민이 필요합니다. `아직 KoBART 토크나이저가 QA 모델에 대해서는 호환되지 않는 것인지에 대해서 질문` 부분은 연구 주제가 되지 않을까 합니다. KoBART모델에서는 이 부분에 대해서 어떠한 제안과 제한을 하고 있지 않습니다. ^^

**Comment by nonmetal** [comment]
아 그렇군요. `PreTrainedTokenizerFast`와 BART 모델 구조에 대해 더 알아보도록 하겠습니다 :) 
답변 감사합니다!
